/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return API readiness information including DB status and uptime.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Config
         * @description Return the persisted configuration (creates defaults if absent).
         */
        get: operations["read_config_api_config_get"];
        /**
         * Update Config
         * @description Update persisted configuration.
         */
        put: operations["update_config_api_config_put"];
        /**
         * Create Config
         * @description Create the configuration entry when it does not yet exist.
         */
        post: operations["create_config_api_config_post"];
        /**
         * Delete Config
         * @description Delete the existing configuration entry.
         */
        delete: operations["delete_config_api_config_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Chat
         * @description Proxy streaming chat responses as SSE events.
         */
        post: operations["stream_chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return cached model metadata augmented with usage warnings.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show Model
         * @description Proxy Ollama `show` endpoint.
         */
        get: operations["show_model_api_models__name__get"];
        put?: never;
        post?: never;
        /**
         * Delete Model
         * @description Delete a local model via Ollama.
         */
        delete: operations["delete_model_api_models__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pull Model
         * @description Stream progress from the Ollama pull endpoint via SSE.
         */
        post: operations["pull_model_api_models_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Model
         * @description Load a model into memory using `ollama run`.
         */
        post: operations["load_model_api_models_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unload Model
         * @description Unload a running model using `ollama stop`.
         */
        post: operations["unload_model_api_models_unload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Rename Session */
        patch: operations["rename_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_sessions__session_id__messages_get"];
        put?: never;
        /** Create Message */
        post: operations["create_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Message */
        delete: operations["delete_message_api_sessions__session_id__messages__message_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages/{message_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Pin */
        post: operations["toggle_pin_api_sessions__session_id__messages__message_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages/{message_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Regeneration */
        post: operations["request_regeneration_api_sessions__session_id__messages__message_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Metrics */
        get: operations["session_metrics_api_sessions__session_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Title */
        post: operations["generate_title_api_title_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Call Ollama's /api/version endpoint for connectivity validation.
         */
        get: operations["get_version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description Request body for the streaming chat endpoint.
         */
        ChatRequest: {
            /** Session Id */
            session_id: number;
            /** Prompt */
            prompt?: string | null;
            /** Model */
            model?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            options?: components["schemas"]["PromptOptions"] | null;
            /** Regenerate Message Id */
            regenerate_message_id?: number | null;
        };
        /**
         * ConfigCreate
         * @description Schema used for creating configuration entries.
         */
        ConfigCreate: {
            /**
             * Ollama Base Url
             * Format: uri
             */
            ollama_base_url: string;
            generation_defaults?: components["schemas"]["GenerationDefaults"];
            /**
             * Theme
             * @default system
             */
            theme: string;
        };
        /**
         * ConfigRead
         * @description Response schema for persisted configuration.
         */
        ConfigRead: {
            /**
             * Ollama Base Url
             * Format: uri
             */
            ollama_base_url: string;
            generation_defaults?: components["schemas"]["GenerationDefaults"];
            /**
             * Theme
             * @default system
             */
            theme: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConfigUpdate
         * @description Schema for partial configuration updates.
         */
        ConfigUpdate: {
            /** Ollama Base Url */
            ollama_base_url?: string | null;
            generation_defaults?: components["schemas"]["GenerationDefaults"] | null;
            /** Theme */
            theme?: string | null;
        };
        /**
         * GenerationDefaults
         * @description Model generation default values.
         */
        GenerationDefaults: {
            /**
             * Model
             * @default llama3
             */
            model: string;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Top P
             * @default 0.9
             */
            top_p: number;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Top K */
            top_k?: number | null;
            /** Repeat Penalty */
            repeat_penalty?: number | null;
            /** Context Window */
            context_window?: number | null;
            /** Stop */
            stop?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health endpoint response.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
            /**
             * Db Status
             * @enum {string}
             */
            db_status: "ok" | "error";
            /**
             * Ollama Status
             * @enum {string}
             */
            ollama_status: "ok" | "error" | "unknown";
            /**
             * Scheduler Status
             * @enum {string}
             */
            scheduler_status: "running" | "stopped" | "error";
            /** Model Cache Age Seconds */
            model_cache_age_seconds?: number | null;
            /**
             * Cached Model Count
             * @default 0
             */
            cached_model_count: number;
            model_stats?: components["schemas"]["ModelStats"] | null;
            /** Uptime Seconds */
            uptime_seconds: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /**
         * MessageCreate
         * @description Payload for persisting chat messages.
         */
        MessageCreate: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Model */
            model?: string | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /**
             * Is Pinned
             * @default false
             */
            is_pinned: boolean;
        };
        /**
         * MessageListResponse
         * @description Wrapper for paginated message retrieval.
         */
        MessageListResponse: {
            /** Items */
            items: components["schemas"]["MessageRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * MessageMetrics
         * @description Per-message token metrics.
         */
        MessageMetrics: {
            /** Message Id */
            message_id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
        };
        /**
         * MessagePinRequest
         * @description Toggle a message pin flag.
         */
        MessagePinRequest: {
            /**
             * Pinned
             * @default true
             */
            pinned: boolean;
        };
        /**
         * MessageRead
         * @description Response schema for stored messages.
         */
        MessageRead: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Model */
            model?: string | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /**
             * Is Pinned
             * @default false
             */
            is_pinned: boolean;
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessageRegenerateResponse
         * @description Response payload containing data to trigger regeneration.
         */
        MessageRegenerateResponse: {
            /** Session Id */
            session_id: number;
            /** Assistant Message Id */
            assistant_message_id: number;
            /** Prompt */
            prompt: string;
            /** Model */
            model?: string | null;
        };
        /**
         * ModelActionResponse
         * @description Standard response when performing model actions.
         */
        ModelActionResponse: {
            /** Name */
            name: string;
            /** Message */
            message: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * ModelListResponse
         * @description Envelope describing cached models and scheduler stats.
         */
        ModelListResponse: {
            /** Items */
            items: components["schemas"]["ModelSummary"][];
            /** Last Refreshed */
            last_refreshed: string | null;
            stats?: components["schemas"]["ModelStats"] | null;
        };
        /**
         * ModelNameRequest
         * @description Common payload for model actions.
         */
        ModelNameRequest: {
            /** Name */
            name: string;
        };
        /**
         * ModelPullRequest
         * @description Pull request payload controlling stream behavior.
         */
        ModelPullRequest: {
            /** Name */
            name: string;
            /**
             * Stream
             * @default true
             */
            stream: boolean;
        };
        /**
         * ModelStats
         * @description CPU/GPU snapshot values captured during scheduler runs.
         */
        ModelStats: {
            /** Cpu Percent */
            cpu_percent?: number | null;
            /** Gpu Percent */
            gpu_percent?: number | null;
            /** Memory Percent */
            memory_percent?: number | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * ModelSummary
         * @description Aggregated metadata for a single Ollama model.
         */
        ModelSummary: {
            /** Name */
            name: string;
            /** Digest */
            digest?: string | null;
            /** Size Mib */
            size_mib?: number | null;
            /**
             * Pulled
             * @default false
             */
            pulled: boolean;
            /**
             * Loaded
             * @default false
             */
            loaded: boolean;
            /** Last Modified */
            last_modified?: string | null;
            /** Status */
            status?: string | null;
            /** Sessions */
            sessions?: number[];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * PromptOptions
         * @description Per-request overrides for generation parameters.
         */
        PromptOptions: {
            /** Temperature */
            temperature?: number | null;
            /** Top P */
            top_p?: number | null;
            /** Top K */
            top_k?: number | null;
            /** Repeat Penalty */
            repeat_penalty?: number | null;
            /** Context Window */
            context_window?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Stop */
            stop?: string[] | null;
        };
        /**
         * SessionCreate
         * @description Payload for creating sessions.
         */
        SessionCreate: {
            /** Title */
            title?: string | null;
        };
        /**
         * SessionListResponse
         * @description Envelope for paginated session listings (simple list wrapper).
         */
        SessionListResponse: {
            /** Items */
            items: components["schemas"]["SessionRead"][];
        };
        /**
         * SessionMetricsResponse
         * @description Aggregated metrics for a session.
         */
        SessionMetricsResponse: {
            /** Session Id */
            session_id: number;
            /**
             * Total Prompt Tokens
             * @default 0
             */
            total_prompt_tokens: number;
            /**
             * Total Completion Tokens
             * @default 0
             */
            total_completion_tokens: number;
            /**
             * Total Messages
             * @default 0
             */
            total_messages: number;
            /** Messages */
            messages: components["schemas"]["MessageMetrics"][];
        };
        /**
         * SessionRead
         * @description Session representation.
         */
        SessionRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SessionUpdate
         * @description Payload for updating session properties.
         */
        SessionUpdate: {
            /** Title */
            title: string;
        };
        /**
         * TitleRequest
         * @description Request body for title generation.
         */
        TitleRequest: {
            /** Session Id */
            session_id: number;
            /** Prompt */
            prompt: string;
            /** Model */
            model?: string | null;
        };
        /**
         * TitleResponse
         * @description Response from title generation endpoint.
         */
        TitleResponse: {
            /** Session Id */
            session_id: number;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Proxy response for Ollama version.
         */
        VersionResponse: {
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    read_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRead"];
                };
            };
        };
    };
    update_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_config_api_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_config_api_config_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream_chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    show_model_api_models__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_models__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_model_api_models_pull_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelPullRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_model_api_models_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelNameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unload_model_api_models_unload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelNameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_sessions__session_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_api_sessions__session_id__messages__message_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_pin_api_sessions__session_id__messages__message_id__pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessagePinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_regeneration_api_sessions__session_id__messages__message_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRegenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_metrics_api_sessions__session_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_title_api_title_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TitleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
